### ISSUE TITLE
implement YellowEffect "No Place is Like Home"

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#144]
Title: No Place is Like Home
Description: If your pokemon is of the same type of this cell, it heals 10%hp
effect_image_dialogID:
![8oktf141qol11](https://user-images.githubusercontent.com/32265040/103469534-4126d900-4d66-11eb-8854-d486a06e1833.png)

**Comment by mihaiJianu** [comment]
![Uploading no_place_like_home.png…]()
this one is better eheheh

**Comment by mihaiJianu** [comment]
Also modified the structure of the bootsraps variable for the yellow effect classes call, now its a final static String[]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\Bootstrap.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\createboardsettings\CreateBoardSettings.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\createboardsettings\CreateBoardSettingsBean.java
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data .....done
Committing transaction...
Committed revision 136.

Adding  (bin)  trunk\PokemonGooseGame\app\src\main\res\drawable\no_place_like_home.png
Transmitting file data .done
Committing transaction...
Committed revision 137.
