### ISSUE TITLE
implement YellowCell effect "That little Brat!"

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#145]
title: "That little brat!"
description: "You have been robbed by Burglar psyduck! You lose half of your coins to the plate"
effect_image_dialogID:
![psyduck_maschera](https://user-images.githubusercontent.com/32265040/103469550-8b0fbf00-4d66-11eb-973b-8f7b81b450fd.png)

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\Bootstrap.java
Adding         trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\ThatLittleBrat.java
Adding  (bin)  trunk\PokemonGooseGame\app\src\main\res\drawable\thief.png
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data .....done
Committing transaction...
Committed revision 168.
