### ISSUE TITLE
Implement yellow effect "A challenger approaches"

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#146]
Title: "A challenger approaches"
Description: "An opponent spots you and wants to fight. Roll a dice to see who wins"

A button ROLL will be available
If ROLL is clicked (or the dialog is dismissed in any other way), a random number in range 1-6 will be generated for the user, and another number  will be generated in the same way for the opponent:
- if user score >= opponent score, user wins 20 coins
- else, user pays 20 coins to the plate

effect_image_dialogID:
![1200px-SSBU_Pokemon_Trainer_Solo_Artwork](https://user-images.githubusercontent.com/32265040/103469602-33be1e80-4d67-11eb-992c-4e4768e86e6a.png)

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\Bootstrap.java
Adding         trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\AChallengerApproaches.java
Adding  (bin)  trunk\PokemonGooseGame\app\src\main\res\drawable\ash.png
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data .....done
Committing transaction...
Committed revision 173.
