### ISSUE TITLE
Implement yellow effect "When the bed traps you"

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#147]
Title: When the bed traps you
Description: You feel too tired to even get out of bed. Your pokemon heals 30% health, but you lose 1 turn
effect_image_dialogID:
![images](https://user-images.githubusercontent.com/32265040/103469614-6d8f2500-4d67-11eb-85b6-6172ea7cdb0c.jpg)

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\Bootstrap.java
Adding         trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\WhenTheBedTrapsYou.java
Adding  (bin)  trunk\PokemonGooseGame\app\src\main\res\drawable\sleep.jpg
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data .....done
Committing transaction...
Committed revision 169.
NICEEEEE
