### ISSUE TITLE
Implement yellow effect "It's a trap!"

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#148]
title: It's a trap
description: "The team rocket ambushes you! You manage to escape after an hard fight. -20% health"
effect_image_dialogID:
![61BcnYZ9iFL _AC_SL1440_](https://user-images.githubusercontent.com/32265040/103469653-cf4f8f00-4d67-11eb-8372-baebd4144101.jpg)

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\Bootstrap.java
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Transmitting file data ..done
Committing transaction...
Committed revision 140.

after
Adding         trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\ItsATrap.java
Transmitting file data .done
Committing transaction...
Committed revision 141.
