### ISSUE TITLE
Implement Yellow effect "The tribute of the pious"

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#150]
title: "The tribute of the pious"
description: "You found a legendary pokemon shrine in the woods. You must pay 10 coins to the plate, else your pokemon shall suffer it's  godly wrath, losing 10% health"
effect_image_dialogID:
![RZdIKZb](https://user-images.githubusercontent.com/32265040/103469807-c3fd6300-4d69-11eb-92ea-b210507c3443.png)

**Comment by mihaiJianu** [comment]
Marginal correction done too

Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\boardfactory\procedurallygenerated\BoardFactoryPG.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\ItsATrap.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\NoPlaceLikeHome.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\pokeapi\pokemon\Pokemon.java
Adding  (bin)  trunk\PokemonGooseGame\app\src\main\res\drawable\its_a_trap.png
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data .......done
Committing transaction...
Committed revision 144.

**Comment by mihaiJianu** [comment]
Forgot to change the image,
Added diffrent changes

Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\Bootstrap.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\NoPlaceLikeHome.java
Transmitting file data ..done
Committing transaction...
Committed revision 147.
