### ISSUE TITLE
Localize the app in Italian language

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#176]

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\TheTributeOfThePious.java
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data ...done
Committing transaction...
Committed revision 172.
