### ISSUE TITLE
Clean the Code

### ISSUE THREAD

**Issue by mihaiJianu** [Torkin1/pokemon_goose_game#196]
Add more checkboxes so you can commit part by part
Clean mean add comments too...

- [x] Delete in CoreController the method changeEntityValue and changePlayerValue. line 272, 282
- [x] Delete EntityParam Class
- [x] Delete class PlayerParam
- [x] Delete PlayerParamGroup
- [x] Delete Change entityValueBean and ChangePlayerValueBean
- [x] Delete All the Log and System
- [x] Clean activities Package
- [x] Clean the boardfactory package
- [x] clean the creaboardsettings package
- [x] clean the database package
- [x] clean the entity package
- [x] clean the game package
- [x] clean the selectpokemon package
- [x] clean the sound package
- [x] clean the utilis package
- [x] clean the volley package
- [x] clean the Bootstrap class
- [x] Clean All

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\gameview\AppConstants.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\gameview\Background.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\gameview\BackgroundThread.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\gameview\BitmapBank.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\gameview\Board.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\gameview\GraphicCell.java
Transmitting file data ......done
Committing transaction...
Committed revision 200.

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\boardfactory\BlueCellSettings.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\boardfactory\BoardFactory.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\boardfactory\BoardFactoryType.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\boardfactory\CreateBoardBean.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\boardfactory\procedurallygenerated\BoardFactoryPG.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\boardfactory\procedurallygenerated\CreateBoardPGBean.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\boardfactory\procedurallygenerated\CreateBoardPGHandlerCallback.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\createboardsettings\CreateBoardSettings.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\createboardsettings\CreateBoardSettingsBean.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\database\local\LocalDatabase.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\database\local\boardpgdao\BoardSettingsDao.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\database\pokeapi\DAOPokemon.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\database\pokeapi\DAOSprite.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\database\pokeapi\DAOType.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\database\pokeapi\PokeAPIGetter.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\database\pokeapi\PokeAPIVersion.java
Transmitting file data ................done
Committing transaction...
Committed revision 202.

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\Game.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\Player.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\InvocationContext.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\ItsATrap.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\ItsOnFireYo.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\LittleHiddenTreasure.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\NoPlaceLikeHome.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\OhNoMyPocket.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\ThatBerryLooksTasty.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\ThatLittleBrat.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\TheTributeOfThePious.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\WhenTheBedTrapsYou.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\Win.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\YellowEffectDeck.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\pokeapi\pokemon\Pokemon.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\pokeapi\pokemon\Sprites.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\pokeapi\pokemon\Stats.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\pokeapi\type\DamageRelations.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\pokeapi\type\Type.java
Transmitting file data ...................done
Committing transaction...
Committed revision 204.

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\Bootstrap.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\game\AddNewPlayerBean.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\game\CellInfoBean.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\game\CoreController.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\game\CreateGameBean.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\game\GameFactory.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\game\SkipTurnBean.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\graphics\DialogManager.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\graphics\ToastWithIcon.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\selectpokemon\ControllerSelectPokemon.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\selectpokemon\GetNumOfPokemonBean.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\selectpokemon\LoadPokemonBean.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\selectpokemon\SelectPokemonBean.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\sound\HomeWatcher.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\sound\MusicService.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\utils\DrawableGetter.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\utils\DrawableNotFoundException.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\utils\MethodGetter.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\utils\NoSuchGetterException.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\utils\NoSuchSetterException.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\volley\GsonQueryRequest.java
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-it-rIT\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data ........................done
Committing transaction...
Committed revision 205.

**Comment by mihaiJianu** [comment]
2 things were missing

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\MainActivity.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\addplayer\AddPlayerActivity.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\gameview\GameActivity.java
Transmitting file data ...done
Committing transaction...
Committed revision 212.

**Comment by Torkin1** [comment]
Delete in CoreController the method changeEntityValue and changePlayerValue. line 272, 282
Delete EntityParam Class
Delete class PlayerParam
Delete PlayerParamGroup
Delete Change entityValueBean and ChangePlayerValueBean
