### ISSUE TITLE
Some balance changes to yellow effect "Caught without a mask!"

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#197]
- [x] Player must go back of 6 cells and skip one turn after paying 25 coins to the plate
- [x] new description: "Well well well, what do we have here. This will cost you 25 coins, sir. Now go 6 cells back to your house and stay in quarantine for 1 turn."
- [x] Update italian translation of description

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\CaughtWithoutMask.java
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-it-rIT\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data ....done
Committing transaction...
Committed revision 177.
