### ISSUE TITLE
Balance changes to yellow effect "Oh no my pocket"

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#198]
- [x] Player must lose coins instead of gaining it
- [x] update english and italian description

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\OhNoMyPocket.java
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-it-rIT\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data ....done
Committing transaction...
Committed revision 178.
