### ISSUE TITLE
Music starts on its own when passing from main activity to add player activity

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#204]
steps to reproduce:
- open app
- mute the game
- close the app
- open the app
- click play game

expected behaviour: music should stay disabled

actual behaviour: music is enabled

**Comment by mihaiJianu** [comment]
Done also solved 2 Additional bugs
1. When the activity started from onResume no controls were made if the sound was off or on.
2.  Now if clicked on the home in the MainActivity's menu, the app will simulate an onbackPressed, Also no more toats

Sending        PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\AboutusActivity.java
Sending        PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\InfoActivity.java
Sending        PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\MainActivity.java
Sending        PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\addplayer\AddPlayerActivity.java
Sending        PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\gameview\GameActivity.java
Sending        PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\Effect.java
Transmitting file data ......done
Committing transaction...
Committed revision 187.
