### ISSUE TITLE
Some texts might be cut off screen in effect dialogs

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#205]
current known text glitches:
- [x] "A challenger approaches" description text

**Comment by mihaiJianu** [comment]
![photo6039354777529332692](https://user-images.githubusercontent.com/45464636/104091297-cd606100-527c-11eb-97da-1b1add898fbc.jpg)

Now all the general dialogs are scrollable in case the space isn't enough

Sending        PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\activities\addplayer\AddPlayerActivity.java
Sending        PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\entity\effect\Effect.java
Sending        PokemonGooseGame\app\src\main\res\layout\general_dialog.xml
Sending        PokemonGooseGame\app\src\main\res\values\dimens.xml
Sending        PokemonGooseGame\app\src\main\res\values-it-rIT\strings.xml
Transmitting file data .....done
Committing transaction...
Committed revision 185.
