### ISSUE TITLE
Restyle layout in AddActivityPlayer

### ISSUE THREAD

**Issue by LorenzoMei** [Torkin1/pokemon_goose_game#211]

**Comment by mihaiJianu** [comment]
Sending        PokemonGooseGame\app\src\main\res\values\colors.xml
Sending        PokemonGooseGame\app\src\main\res\values\themes.xml
Sending        PokemonGooseGame\app\src\main\res\values-night\themes.xml
Transmitting file data ...done
Committing transaction...
Committed revision 193.
