### ISSUE TITLE
Fix "tap to roll" text

### ISSUE THREAD

**Issue by LorenzoMei** [Torkin1/pokemon_goose_game#246]

**Comment by mihaiJianu** [comment]
Myabe we can do better

**Comment by mihaiJianu** [comment]
Added a descriptio nto the 2 new elemts
removed unsued linear Layout
resized the dimenions of the  tvRoll
created a common dimenion value

Sending        PokemonGooseGame\app\src\main\res\layout\activity_game.xml
Sending        PokemonGooseGame\app\src\main\res\values\dimens.xml
Sending        PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        PokemonGooseGame\app\src\main\res\values-it-rIT\strings.xml
Sending        PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data .....done
Committing transaction...
Committed revision 236.
