### ISSUE TITLE
Music on main menu doesnt start on its own

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/pokemon_goose_game#57]
It does start if first disabling it and then re-enabling it

**Comment by Torkin1** [comment]
Restarting the activity starts the music too

**Comment by mihaiJianu** [comment]
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\MainActivity.java
Transmitting file data .done
Committing transaction...
Committed revision 130.

**Comment by mihaiJianu** [comment]
For real no regressive bugs this time, I hope at least

**Comment by mihaiJianu** [comment]
Added the isMute string in string, lowered the volume, rearanjed the communications
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\MainActivity.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\graphics\MusicService.java
Sending        trunk\PokemonGooseGame\app\src\main\res\values\strings.xml
Sending        trunk\PokemonGooseGame\app\src\main\res\values-night\strings.xml
Transmitting file data ....done
Committing transaction...
Committed revision 132.
