### ISSUE TITLE
Add Cell proprieties

### ISSUE THREAD

**Issue by mihaiJianu** [Torkin1/pokemon_goose_game#92]

**Comment by Torkin1** [comment]
cell title for blue cells, type

**Comment by mihaiJianu** [comment]
- Added new cell proprieties, as cell and type
- Now the page number its settled in bottom-right area
- Exchagine the vector images with pngs, because couldn't be casted to Bitmap
- Removed old unused methods from BitmapBank
- Added new method for rescaling the type icons, in BitmapBank


Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\graphics\BitmapBank.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\graphics\GameEngine.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\graphics\GameView.java
Sending        trunk\PokemonGooseGame\app\src\main\java\it\walle\pokemongoosegame\graphics\PokePawn.java
All the images swapped
Committed revision 88.
