### ISSUE TITLE
Track Pawn position and displaying page using the already existing methodology

### ISSUE THREAD

**Issue by mihaiJianu** [Torkin1/pokemon_goose_game#94]
Use Point to get the position and increase with the Constants already in the classes

**Comment by Torkin1** [comment]
- [x] Create a pawn for every registered player
- [x] Pawns positions must be updated whenever the board screen is updated
- [x] Draw pawns on screen only if their cell is in the current board page
- [x] make getInstance method Synchronized of singleton classes used by surface updater threads
- [x] Make constants of how many cells fit in  a row and a column (and move them away from app constants to avoid dependency loop between BitmapBank and AppConstants)
- [x] make surface updater threads die on acitvity pause and restart on activity resume
